apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
        - name: weatherapp
          image: ${{ secrets.DOCKER_USERNAME }}/weatherapp:${{ github.event.release.tag_name }}
          ports:
            - containerPort: 5000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-api-secret
                  key: API_KEY
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
spec:
  type: LoadBalancer
  selector:
    app: weatherapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000