name: Release build test

on:
  push:
    branches:
      [main]
  
jobs:
  build:
   runs-on: ubuntu-latest
    
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: build docker image with release version
      run: docker build . -t weatherapp:latest 

    - name: login to docker hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

 
    - name: push image to dockerhub
      run: docker push ${{secrets.DOCKER_USERNAME}}/weatherapp:latest



