name: Release build test

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/weatherapp
      RELEASE_VERSION: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image with release version
        run: docker build . \
           --build-arg APP_VERSION=${RELEASE_VERSION} \
           -t $IMAGE_NAME:$RELEASE_VERSION

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push $IMAGE_NAME:$RELEASE_VERSION
