name: Release build test

on:
  push:
    branches:
      [main]
  
jobs:
  build:
   runs-on: ubuntu-latest
    
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: build docker image with release version
      run: docker build . -t weatherapp:latest 

    - name: login to docker hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.Docker_Username }}
          password: ${{ secrets.Docker_Password }} 

 
    - name: push image to dockerhub
      run: docker push ${{secrets.Docker_Username}}/weatherapp:latest



