name: Release build test

on:
  release:
    types:
      [published]
  
jobs:
  build:
   runs-on: ubuntu-latest

   env:
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
    

    
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: build docker image with release version
      run: docker build . -t ${{secrets.DOCKER_USERNAME}}/weatherapp:$RELEASE_VERSION
    
      
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

 
    - name: push image to dockerhub
      run: docker push ${{secrets.DOCKER_USERNAME}}/weatherapp:$RELEASE_VERSION



