name: Release build test

on:
  push:
    branches:
      [main]
  
jobs:
  build:
   runs-on: ubuntu-latest
    
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: build docker image with release version
      run: docker build . -t weatherapp:latest 
    
    - name: Debug secrets (for testing only)
      run: |
      echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME != '' }}"
      echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD != '' }}"

    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

 
    - name: push image to dockerhub
      run: docker push ${{secrets.DOCKER_USERNAME}}/weatherapp:latest



