name: Release build

on:
  [workflow_dispatch]
  
jobs:
  build:
   runs-on: ubuntu-latest
    
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: build docker image with release version
      run: docker build -t ${{secrets.Docker_Username}}/weatherapp:latest

    - name: login to docker hub
      run: docker login -u ${{secrets.Docker_Username}} -p {{secrets.Docker_Password}}

 
    - name: push image to dockerhub
      uses: docker push ${{secrets.Docker_Username}}/weatherapp:latest



